name: MMOCore
version: '${project.version}'
main: me.logan.mmocore.MMOCore
api-version: '1.20'
commands:
  dev:
    description: "Dev Command"
  party:
    description: Party command
    usage: /party <option>
    alias: group
  profile:
    description: Profile command
    usage: /profile <option>